---
- name: Create Users
  hosts: all
  become: yes

  tasks:
    - name: Create users
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
      loop:
        - devops
        - testuser
        - adminuser
